### ISSUE TITLE
PostCSS API cleaning

### ISSUE THREAD

**Issue by ai** [postcss/postcss#192]
PostCSS API has some confused parts, because when I start project I didn’t understand how developers will use them.

After `4.1` I plan to release major `5.0`. Maybe it is time to clean API until we have not so many plugin?

Current ideas:

* [ ] Rename `postcss.atRule` to `postcss.atrule` #183
* [x] Rename `PostCSS` class to `Processor` #186
* [ ] Do not clone nodes in insert methods #187 by @MoOx
* [x] Remove `replaceWith` or `replace` #188
* [x] `Node#remove` instead of 2 remove methods #191
* [ ] Insert methods should return new node #193
* [x] Remove Root#prevMap #194
* [ ] Code style properties refector #199
* [x] Remove return Root support from plugin #231
* [x] Rename error.generated #241
* [x] Rename raw properties #244

@MoOx @yisibl @lydell @hail2u let’s collect all your wished and angry here.

**Comment by ai** [comment]
Current ideas:

* Rename `postcss.atRule` to `postcss.atrule` #183
* Rename `PostCSS` class to `Processor` #186
* Do not clone nodes in insert methods #187 by @MoOx
* Remove `replaceWith` or `replace` #188
* `Node#remove` instead of 2 remove methods #191

**Comment by MoOx** [comment]
Clean & stabilize please. So I do not have to update plugins all the times :)

**Comment by hail2u** [comment]
Before renaming API, you should categorize which API is stable and which is not, I think (and want).

**Comment by ai** [comment]
* Insert methods should return new node #193

**Comment by ai** [comment]
@MoOx I totally agree, that we have to much major releases. I will try to avoid major releases after 5.0.

@hail2u sorry, but I am not ready to 100% freeze API right now. Web developing is too fast :). Maybe after a year?

**Comment by ai** [comment]
- [ ] Remove Root#prevMap #194

**Comment by lydell** [comment]
It might be a good idea to look at recent DOM specs, jQuery and other AST libs to see what people commonly do with trees and nodes and to look for good/familiar method names.

**Comment by MoOx** [comment]
jQuery is on of the worst API I know. Please don't mimic it. Having getter and setter in one method is just horrible and dangerous.

**Comment by ai** [comment]
@MoOx I am agree about getter/setter method. DOM API is more relevant for us.

**Comment by davidtheclark** [comment]
I wonder if you might want to add to the API parsing of simple selectors (extracting them from the selectors)? I did this to make [list-selectors](https://github.com/davidtheclark/list-selectors) and I know it would also be useful for linters, and maybe other plugins. Just an idea.

**Comment by jonathantneal** [comment]
Here is a translation of [the DOM4 API](https://dom.spec.whatwg.org/) that you might follow.

### Node#before()

The **Node#before()** method inserts specified nodes before the current node.

#### Example

Insert two declarations before the current declaration.

```js
declaration.before({
	prop: "text-align",
	value: "center"
}, {
	prop: "text-decoration",
	value: "underline"
});
```

---

### Node#after()

The **Node#after()** method inserts specified nodes before the current node.

#### Example

Insert three declarations after the current declaration.

```js
declaration.after({
	prop: "text-indent",
	value: "1em"
}, {
	prop: "text-rendering",
	value: "optimizeLegibility"
}, {
	prop: "text-transform",
	value: "uppercase"
});
```

---

### Node#append()

The **Node#append()** method inserts specified nodes after the last child of the current node.

#### Example

Insert five declarations at the end of the current rule.

```js
rule.append({
	prop: "position",
	value: "absolute"
}, {
	prop: "top",
	value: "0"
}, {
	prop: "right",
	value: "0"
}, {
	prop: "bottom",
	value: "0"
}, {
	prop: "left",
	value: "0"
});
```

---

### Node#prepend()

The **Node#prepend()** method inserts specified nodes before the first child of the current node.

#### Example

Insert two declarations at the beginning of the current rule.

```js
rule.prepend({
	prop: "margin",
	value: "0"
}, {
	prop: "padding",
	value: "0"
});
```

---

### Node#remove()

The **Node#remove()** method removes the current node from its parent.

#### Example

Remove the current declaration.

```js
declaration.remove();
```

---

### Node#replaceWith()

The **Node#replaceWith** method replaces the current node with specified nodes.

#### Example

Replace the current declaration with two declarations.

```js
declaration.replaceWith({
	prop: "-moz-appearance",
	value: "none"
}, {
	prop: "-webkit-appearance",
	value: "none"
});
```

---

**Comment by jedmao** [comment]
Have you considered dumping these issues into milestones for major and minor release versions for tracking? Personally, I like how it's done in the [Microsoft TypeScript Milestones](https://github.com/Microsoft/TypeScript/milestones).

**Comment by ai** [comment]
I will cose this issue, because anyway seems like a forget to updated it.
